[package]
name = "kamaitachi"
version = "0.1.0"
authors = ["keiya01 <keiya.s.0210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
